import {test} from 'node:test';import assert from 'node:assert/strict';import {fixture,manifest,searchRows} from './provider.mjs';
test('declared enterprise dimensions and disjoint memberships are facts',()=>{const d=fixture();assert.equal(d.rows.filter(r=>r.state==='OPEN').length,manifest.openPrs);assert.equal(new Set(d.rows.map(r=>r.id)).size,manifest.openPrs+manifest.historicalMerged);assert.equal(new Set(d.rows.map(r=>r.repository.nameWithOwner)).size,50);assert.equal(new Set(d.rows.map(r=>r.author.login)).size,50);const authored=searchRows(d.rows,'is:pr is:open author:@me');const reviewing=searchRows(d.rows,'is:pr is:open review-requested:@me');assert.equal(authored.length,50);assert.equal(reviewing.length,150);assert.equal(authored.filter(a=>reviewing.includes(a)).length,0);assert.equal(searchRows(d.rows,'is:pr is:open repo:synthetic-lab/repo-1').length,4);assert.equal(searchRows(d.rows,'is:pr is:merged org:synthetic-lab').length,250);assert.throws(()=>searchRows(d.rows,'unrecognized:filter'));});
import {startProvider} from './provider.mjs';
async function usingProvider(run){const p=await startProvider();try{await run(p,async query=>{const r=await fetch(p.url+'/graphql',{method:'POST',body:JSON.stringify({query}),headers:{'content-type':'application/json'}});assert.equal(r.status,200);return (await r.json()).data;});}finally{await p.close();}}
test('unknown organization, repository owner/name, and wrong PR repository do not return fallback facts',()=>usingProvider(async(_p,query)=>{const d=await query('{ organization(login:"absent"){login} repository(owner:"absent",name:"repo-1"){nameWithOwner} wrong:repository(owner:"synthetic-lab",name:"repo-2"){pullRequest(number:51){id}} }');assert.equal(d.organization,null);assert.equal(d.repository,null);assert.equal(d.wrong.pullRequest,null);}));
test('close transition agrees across search and direct identity reads',()=>usingProvider(async(p,query)=>{p.fault.closed=[51];const d=await query('{ search(query:"is:pr is:open repo:synthetic-lab/repo-1",first:100){nodes{id}} node(id:"PR_51"){id state closedAt} }');assert.equal(d.search.nodes.some(n=>n.id==='PR_51'),false);assert.equal(d.node.state,'CLOSED');assert.ok(d.node.closedAt);}));
test('review receipt preserves explicitly requested commit instead of inventing current-head confirmation',()=>usingProvider(async(_p,query)=>{const d=await query('mutation {addPullRequestReview(input:{pullRequestId:"PR_51",event:APPROVE,commitOID:"stale-head"}){pullRequestReview{commit{oid} pullRequest{headRefOid}}}}');assert.equal(d.addPullRequestReview.pullRequestReview.commit.oid,'stale-head');assert.equal(d.addPullRequestReview.pullRequestReview.pullRequest.headRefOid,'head-51');}));
test('activity facts match requested repository branch and current head',()=>usingProvider(async(p)=>{const response=await fetch(p.url+'/repos/synthetic-lab/repo-1/activity?ref=refs%2Fheads%2Ftopic-51&per_page=10');assert.equal(response.status,200);const [activity]=await response.json();assert.equal(activity.after,'head-51');assert.equal(activity.actor.login,p.data.rows[50].author.login);const absent=await fetch(p.url+'/repos/absent/repo-1/activity');assert.equal(absent.status,404);}));

test('historical PR head and commit agree and occupy a recent closed day',()=>{for(const row of fixture().rows.filter(r=>r.state==='MERGED')){assert.equal(row.commits.nodes[0].commit.oid,row.headRefOid);assert.equal(row.mergedAt.slice(0,10),manifest.historyClosedDay);assert.ok(Date.now()-Date.parse(row.mergedAt)>0);assert.ok(Date.now()-Date.parse(row.mergedAt)<2*86400000);}});

test('synthetic advisory ledger attributes actual production-shaped downward/upward/activity identities',()=>usingProvider(async(p,query)=>{
 await query('query PrStack {repository(owner:"synthetic-lab",name:"repo-1"){pullRequest(number:51){number headRefOid}}}');
 await query('query PrStackUp {repository(owner:"synthetic-lab",name:"repo-1"){pullRequests(baseRefName:"topic-51",first:10){nodes{number}}}}');
 await fetch(p.url+'/repos/synthetic-lab/repo-1/activity?ref=refs%2Fheads%2Ftopic-51');
 assert.deepEqual(p.ledger.map(e=>({stage:e.stage,subjects:e.subjects})),[
  {stage:'stack-down',subjects:[{repo:'synthetic-lab/repo-1',number:51}]},
  {stage:'stack-up',subjects:[{repo:'synthetic-lab/repo-1',number:51}]},
  {stage:'pusher-activity',subjects:[{repo:'synthetic-lab/repo-1',number:51}]},
 ]);
}));
