import assert from 'node:assert/strict';
import test from 'node:test';
import {fixture} from './provider.mjs';
import {replayWarmFixture} from './warm-tail.mjs';
function setup(){
 const data=fixture(),approved=[51,52,53].map(n=>`synthetic-lab/repo-${n-50}/${n}`),source=Array.from({length:148},(_,i)=>{const n=i+51;return `synthetic-lab/repo-${(n-1)%50+1}/${n}`;}).sort(),eligible=source.filter(r=>!approved.includes(r));
 const actions=[51,52,53].map(number=>{const row=data.rows.find(r=>r.number===number),repo=row.repository.nameWithOwner;return {role:number===52?'paired':'desktop',status:200,request:{number,repo,id:row.id,expected_head:row.headRefOid,expected_viewer:'synthetic-viewer',verdict:'approve'},response:{[number===52?'wire':'value']:{outcome:'acknowledged',receipt:{number,repo,pr_id:row.id,commit_oid:row.headRefOid,actor:'synthetic-viewer',state:'APPROVED',review_id:`REVIEW_${number}`,submitted_at:'2026-10-04T12:00:00Z'}}}};});
 const original={shutdown:{clean:true,telemetryLost:false},exit:{code:0},soak:{approved,obligations:{externalClose:true,historyMeasured:true,mountedStats:true},checkpoints:[{stats:{window:{to:'2026-10-04',from:'2026-09-05'}},inventory:{desktop:{reviewing:source},paired:{reviewing:source},displayed:eligible}}]}};
 return {data,original,actions,writes:Array.from({length:3},()=>({operation:'review-write',status:200,terminal:'response-sent'}))};
}
test('warm simulator replays exact acknowledged prior facts without adding current-session writes',()=>{const x=setup(),result=replayWarmFixture(x.data,x.original,x.writes,x.actions);assert.equal(result.source.length,148);assert.equal(result.eligible.length,145);assert.equal(x.data.rows.filter(r=>r.state==='OPEN').length,198);assert.equal(x.data.rows.find(r=>r.number===199).state,'MERGED');assert.equal(x.data.rows.find(r=>r.number===200).state,'CLOSED');assert.equal(x.data.rows.find(r=>r.number===51).reviews.nodes[0].commit.oid,'head-51');assert.equal(x.writes.length,3);});
for(const [name,mutate] of Object.entries({pairedWrongEnvelope:x=>{x.actions[1].response={value:x.actions[1].response.wire};},desktopWrongEnvelope:x=>{x.actions[0].response={wire:x.actions[0].response.value};},pairedMissingEnvelope:x=>{x.actions[1].response={};},bothEnvelopes:x=>{x.actions[0].response.wire=x.actions[0].response.value;},missingRole:x=>{delete x.actions[0].role;},wrongRole:x=>{x.actions[1].role='desktop';},oldHead:x=>{x.actions[0].response.value.receipt.commit_oid='old';},wrongActor:x=>{x.actions[0].response.value.receipt.actor='other';},uncertain:x=>{x.actions[0].response.value.outcome='unknown';},missingAction:x=>{x.actions.pop();},missingSource:x=>{x.original.soak.checkpoints[0].inventory.desktop.reviewing=[];},failedProvider:x=>{x.writes[0].status=503;},noCompleteHistory:x=>{x.original.soak.obligations.historyMeasured=false;},loss:x=>{x.original.shutdown.telemetryLost=true;}}))test(`warm setup rejects ${name}`,()=>{const x=setup();mutate(x);assert.throws(()=>replayWarmFixture(x.data,x.original,x.writes,x.actions));});
