//! Terraform providers, read from `.terraform.lock.hcl`.
//!
//! The only ecosystem here that needs no tool installed. The lock file
//! carries the resolved version in plain text, and the newest comes from
//! the registry over HTTP -- so unlike every other one, a missing
//! `terraform` binary cannot make this report nothing, which is the
//! failure mode #418 was entirely about.
//!
//! Parsed with a line scan rather than an HCL parser. The block this
//! reads is machine-generated by `terraform init` and its shape is
//! fixed:
//!
//! ```text
//! provider "registry.terraform.io/hashicorp/archive" {
//!   version     = "2.8.0"
//!   constraints = ">= 2.4.0"
//! ```
//!
//! A parser would be a dependency for two fields whose format Terraform
//! controls and does not vary.

use super::model::{Bump, Ecosystem, FileScan, Outdated};
use std::path::Path;

/// How deep to look for lock files.
///
/// A Terraform repository is commonly many rooted modules rather than
/// one: on a real one, `modules/*/` and `environments/*/` each hold
/// their own lock. Matching only the root would find nothing at all
/// there.
const MAX_DEPTH: usize = 3;

/// Every provider pinned anywhere in this repository.
///
/// The `Vec`-only view, for a caller that only asks "is there anything
/// here" -- `detect::projects`. Anything RENDERING the result wants
/// `scan`, because this shape cannot say that a lock file was skipped.
pub fn pinned(repo: &Path) -> Vec<Outdated> {
    scan(repo).outdated
}

/// Every provider pinned anywhere in this repository, and every lock file
/// that could not be read.
///
/// `latest` is left EQUAL to `current` and `bump` is `Unknown`: this
/// pass reports what is installed, and `registry::enrich` fills in what
/// is available. Reporting an unknown latest as an update would be the
/// confidently-wrong answer this module exists to avoid.
///
/// A lock file the walk PROVED exists and then could not read is
/// reported, not skipped (#954). It holds an unknown number of providers,
/// so dropping it silently shortens the list by an amount nothing on
/// screen accounts for -- and an empty list on this page reads as "up to
/// date". `error` was hardcoded `None` for Terraform precisely because
/// there is no command to fail here, which left every file-read failure
/// unrepresentable.
pub fn scan(repo: &Path) -> FileScan {
    let mut scan = FileScan::default();
    let (locks, unreadable_dirs) = lock_files(repo);
    for dir in unreadable_dirs {
        // A directory that could not be listed may hold any number of
        // lock files, so it is a bigger unknown than a single file and
        // must not be silently treated as empty.
        scan.failed_with(&dir, "directory could not be listed");
    }
    let mut out = Vec::new();
    for lock in locks {
        let text = match std::fs::read_to_string(&lock) {
            Ok(t) => t,
            Err(e) => {
                scan.failed(&lock, &e);
                continue;
            }
        };
        // The path RELATIVE to the repo, so a row says which module it
        // came from -- with many locks per repo, the bare filename would
        // be the same string a dozen times.
        let manifest = lock
            .strip_prefix(repo)
            .unwrap_or(&lock)
            .to_string_lossy()
            .to_string();
        // A lock file that READ and yielded nothing is not a failure:
        // `terraform init` writes one with no provider blocks when a
        // module has no providers, and calling that unreadable would turn
        // a correct empty answer into a false alarm.
        for (name, version) in providers(&text) {
            out.push(Outdated {
                name,
                current: version.clone(),
                latest: version,
                bump: Bump::Unknown,
                ecosystem: Ecosystem::Terraform,
                manifest: manifest.clone(),
            });
        }
    }
    scan.outdated = out;
    scan
}

/// `(source, version)` for each provider block.
///
/// The source is the full registry address -- `registry.terraform.io/
/// hashicorp/archive` -- because that IS the lookup key, and shortening
/// it here would mean reconstructing it later.
fn providers(text: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let mut current: Option<String> = None;
    for line in text.lines() {
        let t = line.trim();
        if let Some(rest) = t.strip_prefix("provider ") {
            current = rest
                .trim()
                .trim_start_matches('"')
                .split('"')
                .next()
                .map(str::to_string)
                .filter(|s| !s.is_empty());
        } else if let Some(name) = current.clone() {
            if let Some(rest) = t.strip_prefix("version") {
                if let Some(v) = rest.split('"').nth(1) {
                    out.push((name, v.to_string()));
                    // One version per block; anything after it belongs
                    // to hashes until the next `provider`.
                    current = None;
                }
            }
        }
    }
    out
}

/// Lock files under `repo`, to `MAX_DEPTH`, and the directories that could
/// not be listed.
///
/// The second half is returned rather than swallowed, for the reason
/// `claude::transcript::session_files` returns its own: an unreadable
/// directory may hold any number of lock files, and treating it as empty is
/// indistinguishable from it genuinely being empty.
fn lock_files(repo: &Path) -> (Vec<std::path::PathBuf>, Vec<std::path::PathBuf>) {
    const SKIP: &[&str] = &[".git", ".terraform", "node_modules", "target", ".worktrees"];
    let mut out = Vec::new();
    let mut unreadable = Vec::new();
    let mut stack = vec![(repo.to_path_buf(), 0usize)];
    while let Some((dir, depth)) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            unreadable.push(dir);
            continue;
        };
        for e in entries.flatten() {
            let path = e.path();
            let name = e.file_name().to_string_lossy().to_string();
            if path.is_dir() {
                if depth < MAX_DEPTH && !SKIP.contains(&name.as_str()) {
                    stack.push((path, depth + 1));
                }
            } else if name == ".terraform.lock.hcl" {
                out.push(path);
            }
        }
    }
    out.sort();
    // Both sorted: directory order is not stable across machines, and the
    // report should not reshuffle between scans.
    unreadable.sort();
    (out, unreadable)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The REAL shape `terraform init` writes, including the hashes
    /// block that follows the version and must not be mistaken for one.
    const LOCK: &str = r#"
provider "registry.terraform.io/hashicorp/archive" {
  version     = "2.8.0"
  constraints = ">= 2.4.0"
  hashes = [
    "h1:WB6H5ksIZiyq1lQlD/PWeh+tn4FLsbSjVnRW3+4xe2Y=",
  ]
}

provider "registry.terraform.io/hashicorp/aws" {
  version     = "5.100.0"
  constraints = ">= 5.0.0"
}
"#;

    #[test]
    fn reads_each_provider_and_its_version() {
        let got = providers(LOCK);
        assert_eq!(
            got,
            vec![
                (
                    "registry.terraform.io/hashicorp/archive".into(),
                    "2.8.0".into()
                ),
                (
                    "registry.terraform.io/hashicorp/aws".into(),
                    "5.100.0".into()
                ),
            ]
        );
    }

    /// The FULL address, not a shortened name: it is the registry lookup
    /// key, and shortening it here means rebuilding it later.
    #[test]
    fn keeps_the_whole_registry_address() {
        let got = providers(LOCK);
        assert!(got[0].0.starts_with("registry.terraform.io/"));
    }

    /// A `constraints` line is not a version, and neither is a hash.
    #[test]
    fn does_not_mistake_other_lines_for_a_version() {
        assert_eq!(providers(LOCK).len(), 2, "exactly one version per block");
    }

    /// ONE version per block, even when a later line also starts with
    /// the word.
    ///
    /// Real lock files carry `version_constraints` and hash entries
    /// after the version, and without closing the block on the first
    /// match a second line would be read as another provider at a
    /// different version -- the same dependency reported twice, at odds
    /// with itself.
    #[test]
    fn a_second_version_line_in_one_block_is_ignored() {
        let lock = r#"
provider "registry.terraform.io/hashicorp/aws" {
  version     = "5.100.0"
  version_constraints = "9.9.9"
}
"#;
        let got = providers(lock);
        assert_eq!(got.len(), 1, "one provider, not two: {got:?}");
        assert_eq!(got[0].1, "5.100.0");
    }

    #[test]
    fn an_empty_or_unrelated_file_yields_nothing() {
        assert!(providers("").is_empty());
        assert!(providers("# just a comment\nfoo = 1\n").is_empty());
    }

    /// Every row reports Unknown until the registry says otherwise.
    /// Claiming `latest == current` means "up to date" would be the
    /// confidently-wrong answer.
    #[test]
    fn pinned_rows_start_uncompared() {
        let t = tempfile::TempDir::new().unwrap();
        std::fs::write(t.path().join(".terraform.lock.hcl"), LOCK).unwrap();
        let out = pinned(t.path());
        assert_eq!(out.len(), 2);
        for o in &out {
            assert_eq!(o.bump, Bump::Unknown);
            assert_eq!(o.latest, o.current);
        }
    }

    /// A real repo pins per module, so the row must say WHICH.
    #[test]
    fn finds_locks_in_nested_modules() {
        let t = tempfile::TempDir::new().unwrap();
        let deep = t.path().join("modules").join("data");
        std::fs::create_dir_all(&deep).unwrap();
        std::fs::write(deep.join(".terraform.lock.hcl"), LOCK).unwrap();
        let out = pinned(t.path());
        assert_eq!(out.len(), 2);
        // Compared with the platform's OWN separator: `Path::join`
        // produces `modules\\data` on Windows, and a hardcoded forward
        // slash fails there for a correct result.
        let expected = Path::new("modules").join("data");
        assert!(
            out[0].manifest.contains(&*expected.to_string_lossy()),
            "the row must name its module: {}",
            out[0].manifest
        );
    }

    /// A lock file proven to exist and dropped unread (#954).
    ///
    /// `error` was hardcoded `None` for Terraform because there is no
    /// command to fail, so a read failure beneath it was unrepresentable and
    /// the page reported the repository as up to date.
    ///
    /// `#[cfg(unix)]` because `chmod 000` is the mechanism and Windows does
    /// not honour it -- a `0o000` file stays readable there, so this test
    /// would fail for a reason unrelated to the code. The behaviour is not
    /// platform-specific; only this way of producing an unreadable file is.
    #[cfg(unix)]
    #[test]
    fn an_unreadable_lock_file_is_reported_not_dropped() {
        use std::os::unix::fs::PermissionsExt;
        let t = tempfile::TempDir::new().unwrap();
        let lock = t.path().join(".terraform.lock.hcl");
        std::fs::write(&lock, LOCK).unwrap();
        std::fs::set_permissions(&lock, std::fs::Permissions::from_mode(0o000)).unwrap();

        let got = scan(t.path());

        // Restored before any assertion can panic, so a failure cannot
        // leave an undeletable file behind.
        std::fs::set_permissions(&lock, std::fs::Permissions::from_mode(0o644)).unwrap();

        assert!(got.is_partial(), "{got:?}");
        assert!(
            got.error().is_some(),
            "an empty provider list with no error reads as 'up to date': {got:?}"
        );
    }

    /// A lock file that READS and declares no providers is a real answer.
    ///
    /// `terraform init` writes one for a module with no providers, so calling
    /// that unreadable would turn a correct empty answer into a false alarm
    /// -- the false-positive half of the same mistake.
    #[test]
    fn a_lock_file_with_no_providers_is_not_a_failure() {
        let t = tempfile::TempDir::new().unwrap();
        std::fs::write(t.path().join(".terraform.lock.hcl"), "# nothing here").unwrap();

        let got = scan(t.path());

        assert!(!got.is_partial(), "{got:?}");
        assert_eq!(got.error(), None);
    }

    /// A partial answer is labelled partial, NOT discarded.
    #[cfg(unix)]
    #[test]
    fn the_readable_lock_files_survive_an_unreadable_sibling() {
        use std::os::unix::fs::PermissionsExt;
        let t = tempfile::TempDir::new().unwrap();
        std::fs::write(t.path().join(".terraform.lock.hcl"), LOCK).unwrap();
        let nested = t.path().join("modules").join("vpc");
        std::fs::create_dir_all(&nested).unwrap();
        let shut = nested.join(".terraform.lock.hcl");
        std::fs::write(&shut, LOCK).unwrap();
        std::fs::set_permissions(&shut, std::fs::Permissions::from_mode(0o000)).unwrap();

        let got = scan(t.path());

        std::fs::set_permissions(&shut, std::fs::Permissions::from_mode(0o644)).unwrap();

        assert!(got.is_partial(), "{got:?}");
        assert!(
            !got.outdated.is_empty(),
            "the readable lock's providers survive: {got:?}"
        );
    }

    /// An unreadable DIRECTORY is reported too.
    ///
    /// It may hold any number of lock files, so treating it as empty is
    /// indistinguishable from it genuinely being empty -- the distinction
    /// `claude::registry` draws between a directory and a single file.
    #[cfg(unix)]
    #[test]
    fn an_unreadable_directory_is_reported_not_treated_as_empty() {
        use std::os::unix::fs::PermissionsExt;
        let t = tempfile::TempDir::new().unwrap();
        let nested = t.path().join("environments");
        std::fs::create_dir_all(nested.join("prod")).unwrap();
        std::fs::write(nested.join("prod").join(".terraform.lock.hcl"), LOCK).unwrap();
        std::fs::set_permissions(&nested, std::fs::Permissions::from_mode(0o000)).unwrap();

        let got = scan(t.path());

        std::fs::set_permissions(&nested, std::fs::Permissions::from_mode(0o755)).unwrap();

        assert!(
            got.is_partial(),
            "an unlistable directory hides an unknown number of locks: {got:?}"
        );
    }
}

/// Against a REAL Terraform repository. Ignored: it reads a path
/// outside this one.
///
/// `HEADSTATE_TF_REPO=/path cargo test -- --ignored real_tf --nocapture`
#[cfg(test)]
mod real {
    use super::*;

    #[test]
    #[ignore = "reads a real Terraform repository"]
    fn reports_the_providers_it_finds() {
        let Ok(repo) = std::env::var("HEADSTATE_TF_REPO") else {
            eprintln!("set HEADSTATE_TF_REPO");
            return;
        };
        let out = pinned(Path::new(&repo));
        eprintln!("providers found: {}", out.len());
        let mut seen: Vec<String> = out.iter().map(|o| o.name.clone()).collect();
        seen.sort();
        seen.dedup();
        eprintln!("distinct providers: {}", seen.len());
        for o in out.iter().take(4) {
            eprintln!("  {} {} <- {}", o.name, o.current, o.manifest);
        }
        assert!(
            !out.is_empty(),
            "a real Terraform repo must yield providers"
        );
    }
}
