import { act, cleanup, renderHook } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { afterEach, expect, it, vi } from "vitest";
import type { ReactNode } from "react";
const call=vi.hoisted(()=>vi.fn());
vi.mock("./transport",async original=>({...await original<Record<string,unknown>>(),call}));
import { useStatsBoard } from "./hooks";
afterEach(()=>{cleanup();vi.useRealTimers();vi.restoreAllMocks();call.mockReset();});
it("coalesces visible observers, renews locally and releases on hide without reloading boards",async()=>{
 vi.useFakeTimers();let handle=0;
 call.mockImplementation((name:string)=>Promise.resolve(name==="stats_demand"?{handle:`lease-${++handle}`,owner:{viewer:"fixture",generation:1}}:{}));
 const client=new QueryClient({defaultOptions:{queries:{retry:false}}});
 const wrapper=({children}:{children:ReactNode})=><QueryClientProvider client={client}>{children}</QueryClientProvider>;
 const useBoard= ()=>useStatsBoard({kind:"org",value:"fixture",subject:undefined},"merged",30,true);
 const first=renderHook(useBoard,{wrapper});const second=renderHook(useBoard,{wrapper});
 await act(async()=>{});
 const operations=()=>call.mock.calls.filter(([name])=>name==="stats_demand").map(([,args])=>args.request.op);
 expect(operations()).toEqual(["acquire"]);
 const boards=call.mock.calls.filter(([name])=>name==="stats_board").length;
 await act(async()=>{await vi.advanceTimersByTimeAsync(60_000);});
 expect(operations()).toEqual(["acquire","renew"]);
 first.unmount();await act(async()=>{});expect(operations()).toHaveLength(2);
 const visibility=vi.spyOn(document,"visibilityState","get").mockReturnValue("hidden");
 await act(async()=>{document.dispatchEvent(new Event("visibilitychange"));});
 expect(operations()).toEqual(["acquire","renew","release"]);
 await act(async()=>{await vi.advanceTimersByTimeAsync(180_000);});
 expect(operations()).toHaveLength(3);
 visibility.mockReturnValue("visible");
 await act(async()=>{document.dispatchEvent(new Event("visibilitychange"));});
 expect(operations()).toEqual(["acquire","renew","release","acquire"]);
 expect(call.mock.calls.filter(([name])=>name==="stats_board")).toHaveLength(boards);
 second.unmount();client.clear();
});

it("releases acquisition arriving after unmount and reacquires after renewal refusal",async()=>{
 vi.useFakeTimers();let finish:((value:unknown)=>void)|undefined;
 call.mockImplementation((name:string)=>name==="stats_demand"?new Promise(resolve=>{finish=resolve;}):Promise.resolve({}));
 const client=new QueryClient({defaultOptions:{queries:{retry:false}}});
 const wrapper=({children}:{children:ReactNode})=><QueryClientProvider client={client}>{children}</QueryClientProvider>;
 const useBoard= ()=>useStatsBoard({kind:"org",value:"fixture",subject:undefined},"merged",7,true);
 const first=renderHook(useBoard,{wrapper});await act(async()=>{});first.unmount();
 call.mockImplementation(()=>Promise.resolve({handle:"fresh",owner:{viewer:"fixture",generation:1}}));
 await act(async()=>finish?.({handle:"late",owner:{viewer:"fixture",generation:1}}));
 expect(call.mock.calls.some(([name,args])=>name==="stats_demand" && args.request.op==="release" && args.request.handle==="late")).toBe(true);
 const second=renderHook(useBoard,{wrapper});await act(async()=>{});
 call.mockRejectedValueOnce(new Error("stats lease expired"));
 await act(async()=>{await vi.advanceTimersByTimeAsync(60_000);});
 await act(async()=>{await vi.advanceTimersByTimeAsync(60_000);});
 expect(call.mock.calls.at(-1)?.[1].request.op).toBe("acquire");
 second.unmount();client.clear();
});
