import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { act, cleanup, render, renderHook, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import type { ReactNode } from "react";
const seam = vi.hoisted(() => ({ call: vi.fn(), callbacks: new Set<(event: {payload: unknown}) => void>() }));
vi.mock("./transport", () => ({ call: seam.call, listen: vi.fn(async (name, fn) => { if(name === "source-poll-status") seam.callbacks.add(fn); return () => seam.callbacks.delete(fn); }) }));
import { useUiPrefs } from "./hooks";
import { useSourceRefresh } from "./sourceRefreshHooks";
import { ReviewMeasurementProvider, useReviewPresentation } from "./reviewMeasurement";
import { ReadyStrip } from "../components/ReadyStrip";
import { PR_FIXTURES } from "../fixtures/prs";
import { useFilters } from "../store/filters";
const capture = {epoch:"a".repeat(32),capture:1};
const token = {...capture,id:1};
const rows = [{...PR_FIXTURES[0],is_draft:false,ci:"success" as const,merge:"mergeable" as const,review:"none" as const,in_merge_queue:false}];
function Footer(){ useReviewPresentation("checked", "desktop_footer"); return <span>Checked</span>; }
function Ready(){ const source=useSourceRefresh("reviewing"), {prefs}=useUiPrefs(); return <ReviewMeasurementProvider enabled={prefs?.diagnostic_logging===true} receipt={source.measurementReceipt} selected={false} snapshot={source}><ReadyStrip prs={source.prs??[]} localTools={false}/><Footer/></ReviewMeasurementProvider>; }
afterEach(()=>{cleanup();seam.call.mockReset();seam.callbacks.clear();});
it("keeps cached Ready rows across capture transitions, remounts and old/status-only frames without requests",async()=>{
 const qc=new QueryClient({defaultOptions:{queries:{retry:false}}}); qc.setQueryData(["ui-prefs"],{hidden_views:[],close_hides_to_tray:true,announce_updates:false,claude_integrations_enabled:false,terminal_command:"",stale_venv_days:0,battery_low_percent:0,diagnostic_logging:false});
 useFilters.getState().setFilter("readyMyPushes","show");
 let current=capture;
 seam.call.mockImplementation(async(name)=>name==="set_ui_prefs"?current:name==="get_viewer"?"synthetic":undefined);
 const wrapper=({children}:{children:ReactNode})=><QueryClientProvider client={qc}>{children}</QueryClientProvider>;
 const prefs=renderHook(()=>useUiPrefs(),{wrapper});
 const authored=renderHook(()=>useSourceRefresh("authored"),{wrapper});
 let mounted=render(<Ready/>,{wrapper});
 const emit=(revision:number,receipt_revision:number,measurement_receipt=token,prs:typeof rows|null=rows)=>act(()=>{for(const cb of seam.callbacks)cb({payload:{source:{provider:"github",host:"github.com"},list:"reviewing",session:"desktop",revision,receipt_revision,measurement_receipt,prs,phase:"ready",error:null,coverage:"complete"}});});
 await act(async()=>{}); emit(1,1);
 await act(async()=>{await prefs.result.current.set({hidden_views:[],close_hides_to_tray:true,announce_updates:false,claude_integrations_enabled:false,terminal_command:"",stale_venv_days:0,battery_low_percent:0,diagnostic_logging:true});});
 emit(2,2);
 act(()=>{for(const cb of seam.callbacks)cb({payload:{source:{provider:"github",host:"github.com"},list:"authored",session:"desktop",revision:2,receipt_revision:2,measurement_receipt:token,prs:rows,phase:"ready",error:null,coverage:"complete"}});});
 expect(authored.result.current.measurementReceipt).toEqual(token);
 const events=()=>seam.call.mock.calls.filter(c=>c[0]==="measurement_client_events").flatMap(c=>c[1].batch);
 await waitFor(()=>expect(events().at(-1)?.receipt).toEqual(token));
 await act(async()=>{await prefs.result.current.set({hidden_views:[],close_hides_to_tray:true,announce_updates:false,claude_integrations_enabled:false,terminal_command:"",stale_venv_days:0,battery_low_percent:0,diagnostic_logging:false});});
 mounted.unmount(); const count=events().length;
 current={...capture,capture:2};
 await act(async()=>{await prefs.result.current.set({hidden_views:[],close_hides_to_tray:true,announce_updates:false,claude_integrations_enabled:false,terminal_command:"",stale_venv_days:0,battery_low_percent:0,diagnostic_logging:true});});
 mounted=render(<Ready/>,{wrapper});
 await waitFor(()=>expect(events().length).toBeGreaterThan(count));
 expect(authored.result.current.prs).toBe(rows); expect(authored.result.current.measurementReceipt).toBeUndefined();
 expect(events().at(-1)).toMatchObject({inventory_count:1}); expect(events().at(-1)?.receipt).toBeUndefined();
 expect(screen.getByText(/Ready for review \(1\)/)).toBeTruthy();
 emit(3,2); emit(4,1); emit(5,2,token,null); emit(6,6,token);
 await act(async()=>{});expect(events().at(-1)?.receipt).toBeUndefined();
 const fresh={...current,id:9}; emit(7,7,fresh);
 await waitFor(()=>expect(events().at(-1)?.receipt).toEqual(fresh));
 expect(seam.call.mock.calls.filter(c=>["refresh_source","get_source_snapshot","get_reviewing","stats_board"].includes(c[0]))).toHaveLength(0);
 mounted.unmount();qc.clear();
});
it("publishes no capture on a failed save and fences late successful acknowledgments",async()=>{
 const qc=new QueryClient({defaultOptions:{queries:{retry:false}}}); const initial={hidden_views:[],close_hides_to_tray:true,announce_updates:false,claude_integrations_enabled:false,terminal_command:"",stale_venv_days:0,battery_low_percent:0,diagnostic_logging:true};
 qc.setQueryData(["ui-prefs"],initial);
 const pending:Array<{resolve:(v:unknown)=>void,reject:(e:Error)=>void}>=[];
 seam.call.mockImplementation((name)=>name==="set_ui_prefs"?new Promise((resolve,reject)=>pending.push({resolve,reject})):Promise.resolve(undefined));
 const wrapper=({children}:{children:ReactNode})=><QueryClientProvider client={qc}>{children}</QueryClientProvider>;
 const prefs=renderHook(()=>useUiPrefs(),{wrapper});
 let first!:Promise<void>;act(()=>{first=prefs.result.current.set(initial);});
 await act(async()=>{pending[0].resolve(capture);await first;});
 expect(qc.getQueryData(["measurement-capture"])).toEqual(capture);
 let failed!:Promise<void>;act(()=>{failed=prefs.result.current.set({...initial,diagnostic_logging:false});});
 await act(async()=>{pending[1].reject(new Error("synthetic refusal"));await expect(failed).rejects.toThrow("synthetic refusal");});
 expect(qc.getQueryData(["measurement-capture"])).toEqual(capture);
 expect(qc.getQueryData(["ui-prefs"])).toEqual(initial);
 let old!:Promise<void>,fresh!:Promise<void>;
 act(()=>{old=prefs.result.current.set({...initial,diagnostic_logging:false});fresh=prefs.result.current.set(initial);});
 await act(async()=>{pending[3].resolve({...capture,capture:2});await fresh;});
 await act(async()=>{pending[2].resolve(capture);await old;});
 expect(qc.getQueryData(["measurement-capture"])).toBeNull();
 expect(qc.getQueryData(["ui-prefs"])).toEqual(initial);
 expect(seam.call.mock.calls).toHaveLength(4);qc.clear();
});
it.each(["success-first", "failure-first"] as const)("publishes the earlier successful preference save when the newer request fails (%s)",async order=>{
 const qc=new QueryClient({defaultOptions:{queries:{retry:false}}});
 const initial={hidden_views:[],close_hides_to_tray:true,announce_updates:false,claude_integrations_enabled:false,terminal_command:"",stale_venv_days:0,battery_low_percent:0,diagnostic_logging:true};
 const saved={...initial,close_hides_to_tray:false};
 qc.setQueryData(["ui-prefs"],initial);
 const pending:Array<{resolve:(v:unknown)=>void,reject:(e:Error)=>void}>=[];
 seam.call.mockImplementation((name)=>name==="set_ui_prefs"?new Promise((resolve,reject)=>pending.push({resolve,reject})):Promise.resolve(undefined));
 const wrapper=({children}:{children:ReactNode})=><QueryClientProvider client={qc}>{children}</QueryClientProvider>;
 const prefs=renderHook(()=>useUiPrefs(),{wrapper});
 let earlier!:Promise<void>,later!:Promise<void>;
 act(()=>{earlier=prefs.result.current.set(saved);later=prefs.result.current.set({...saved,announce_updates:true});});
 const succeed=async()=>act(async()=>{pending[0].resolve(capture);await earlier;});
 const fail=async()=>act(async()=>{pending[1].reject(new Error("synthetic save refusal"));await expect(later).rejects.toThrow("synthetic save refusal");});
 if(order==="success-first"){await succeed();await fail();}else{await fail();await succeed();}
 expect(qc.getQueryData(["ui-prefs"])).toEqual(saved);
 await waitFor(()=>expect(prefs.result.current.prefs).toEqual(saved));
 // Product success is publishable even though native capture order remains unproven.
 expect(qc.getQueryData(["measurement-capture"])).toBeNull();
 expect(seam.call.mock.calls).toHaveLength(2);qc.clear();
});
